'use client';
import Link from 'next/link'; import { useEffect, useState } from 'react'; import { api } from '@/lib/data';
type Category = { id: string; name: string };
export default function NewGear() {
 const [message, setMessage] = useState(''); const [categories, setCategories] = useState<Category[]>([]);
 useEffect(() => { const saved = localStorage.getItem('gearup_user'); if (!saved) { window.location.assign('/auth/login'); return; } const user = JSON.parse(saved); if (user.role !== 'PROVIDER') { window.location.assign(`/dashboard/${user.role.toLowerCase()}`); return; } api<Category[]>('/categories').then(setCategories).catch(() => setMessage('Could not load categories.')); }, []);
 async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const token = localStorage.getItem('gearup_token') || ''; try { await api('/provider/gear', { method: 'POST', body: JSON.stringify({ categoryId: f.get('categoryId'), name: f.get('name'), description: f.get('description'), brand: f.get('brand'), pricePerDay: Number(f.get('pricePerDay')), stock: Number(f.get('stock')), availability: true, images: [f.get('image')] }) }, token); setMessage('Gear listed successfully.'); e.currentTarget.reset(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to list gear.'); } }
 return <main className="shell" style={{maxWidth:760,paddingTop:40,paddingBottom:80}}><Link className="muted" href="/dashboard/provider">← Provider dashboard</Link><h1 style={{fontSize:46,letterSpacing:-2}}>List new gear.</h1><p className="muted">Add an item to your GearUp inventory.</p><form onSubmit={submit} className="form" style={{background:'#fff',border:'1px solid #dfe5df',padding:24,borderRadius:16}}><div className="fields"><div className="field"><label>ITEM NAME</label><input name="name" required placeholder="e.g. Summit 2P Tent"/></div><div className="field"><label>BRAND</label><input name="brand" required placeholder="e.g. NOMAD"/></div></div><div className="fields"><div className="field"><label>CATEGORY</label><select name="categoryId" required defaultValue=""><option value="" disabled>Select a category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></div><div className="field"><label>PRICE / DAY ($)</label><input name="pricePerDay" type="number" min="1" required/></div></div><div className="fields"><div className="field"><label>STOCK</label><input name="stock" type="number" min="0" defaultValue="1" required/></div><div className="field"><label>IMAGE URL</label><input name="image" type="url" required placeholder="https://…"/></div></div><div className="field"><label>DESCRIPTION</label><textarea name="description" required rows={4} placeholder="Tell renters about this item…"/></div>{message&&<p className={message.includes('successfully')?'muted':'error'}>{message}</p>}<button className="btn">Publish listing →</button></form></main>;
}
