'use client';
import Link from 'next/link'; import { useEffect, useState } from 'react'; import { useRouter } from 'next/navigation'; import { api } from '@/lib/data';
type Role = 'customer' | 'provider' | 'admin'; const paths = { customer: '/rentals', provider: '/provider/orders', admin: '/admin/users' }; const names = { customer: 'Your rentals', provider: 'Incoming orders', admin: 'Platform users' };
export function Dashboard({ role }: { role: Role }) {
 const [items, setItems] = useState<any[]>([]); const [message, setMessage] = useState('Loading your live data…'); const [notes, setNotes] = useState<Record<string, string>>({}); const [savingId, setSavingId] = useState(''); const router = useRouter();
 useEffect(() => { const token = localStorage.getItem('gearup_token'); const saved = localStorage.getItem('gearup_user'); if (!token || !saved) { router.replace('/auth/login'); return; } try { const user = JSON.parse(saved); const savedRole = typeof user.role === 'string' ? user.role.toLowerCase() : ''; if (!['customer', 'provider', 'admin'].includes(savedRole)) { localStorage.removeItem('gearup_token'); localStorage.removeItem('gearup_user'); router.replace('/auth/login'); return; } if (savedRole !== role) { router.replace(`/dashboard/${savedRole}`); return; } if (role === 'provider') setNotes(JSON.parse(localStorage.getItem('gearup_provider_notes') || '{}')); } catch { localStorage.removeItem('gearup_token'); localStorage.removeItem('gearup_user'); router.replace('/auth/login'); return; } api<any[]>(paths[role], {}, token).then(x => { setItems(x); setMessage(x.length ? '' : 'Nothing to show yet.'); }).catch(e => setMessage(e.message)); }, [role, router]);
 async function updateOrder(id: string, status: string) { const token = localStorage.getItem('gearup_token'); if (!token) { router.replace('/auth/login'); return; } setSavingId(id); try { const updated: any = await api(`/provider/orders/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }, token); setItems(current => current.map(item => item.id === id ? { ...item, ...updated, status: updated.status || status } : item)); setMessage(`Order ${status.toLowerCase().replace('_', ' ')} successfully.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update this order.'); } finally { setSavingId(''); } }
 function saveNote(id: string, value: string) { const next = { ...notes, [id]: value }; setNotes(next); localStorage.setItem('gearup_provider_notes', JSON.stringify(next)); setMessage('Internal note saved on this device.'); }
 const stats = role === 'customer' ? [['Active rentals', items.filter(x => !['RETURNED', 'CANCELLED'].includes(x.status)).length], ['Total orders', items.length], ['Ready to review', items.filter(x => x.status === 'RETURNED').length]] : role === 'provider' ? [['Incoming orders', items.length], ['Awaiting action', items.filter(x => x.status === 'PLACED').length], ['This month', '—']] : [['Total users', items.length], ['Active accounts', items.filter(x => x.status === 'ACTIVE').length], ['Platform status', 'Healthy']];
 return <div className="dash"><aside className="side"><Link href="/" className="brand">gear<i>up</i>.</Link><Link className="active" href={`/dashboard/${role}`}>Overview</Link><Link href="/profile">My profile</Link>{role === 'provider' && <><Link href="/dashboard/provider/gear/new">Add new gear</Link><Link href="/dashboard/provider/inventory">My inventory</Link></>}{role === 'customer' && <Link href="/gear">Browse gear</Link>}<Link href="/">Back to site</Link></aside><main className="content"><span className="eyebrow" style={{ color: '#1d5a45' }}>{role} workspace</span><h1>{role === 'admin' ? 'Keep GearUp moving.' : role === 'provider' ? 'Welcome back, provider.' : 'Your next adventure awaits.'}</h1><div className="stats">{stats.map(([name, value]) => <div className="stat" key={String(name)}><span className="muted">{name}</span><b>{value}</b></div>)}</div><h2>{names[role]}</h2>{message && items.length > 0 && <p className="muted">{message}</p>}<div className="table">{items.length ? <table><thead><tr><th>Item</th><th>Customer / Email</th><th>Status</th><th>Amount</th>{role === 'provider' && <th>Actions & note</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.gear?.name || item.fullName || '—'}</td><td>{item.customer?.fullName || item.email || '—'}</td><td><span className={`badge ${item.status || ''}`}>{item.status || item.role}</span></td><td>{item.totalAmount ? `$${item.totalAmount}` : '—'}</td>{role === 'provider' && <td><div style={{display:'grid',gap:8,minWidth:210}}>{item.status === 'PLACED' && <div style={{display:'flex',gap:6}}><button className="btn" disabled={savingId === item.id} onClick={() => updateOrder(item.id, 'CONFIRMED')} style={{padding:'8px 11px',fontSize:12}}>Confirm</button><button className="btn outline" disabled={savingId === item.id} onClick={() => updateOrder(item.id, 'CANCELLED')} style={{padding:'8px 11px',fontSize:12}}>Cancel</button></div>}{['CONFIRMED', 'PAID'].includes(item.status) && <button className="btn" disabled={savingId === item.id} onClick={() => updateOrder(item.id, 'PICKED_UP')} style={{padding:'8px 11px',fontSize:12}}>Mark picked up</button>}{item.status === 'PICKED_UP' && <button className="btn" disabled={savingId === item.id} onClick={() => updateOrder(item.id, 'RETURNED')} style={{padding:'8px 11px',fontSize:12}}>Mark returned</button>}<input aria-label={`Note for ${item.gear?.name || 'order'}`} placeholder="Internal note…" value={notes[item.id] || ''} onChange={e => saveNote(item.id, e.target.value)} style={{padding:7,border:'1px solid #dfe5df',borderRadius:7,fontSize:12}}/></div></td>}</tr>)}</tbody></table> : <div className="empty">{message}</div>}</div></main></div>;
}
