'use client';
import { useMemo, useState } from 'react';
import { GearCard } from './gear-card';
import type { Gear } from '@/lib/data';
export function GearBrowser({ gear }: { gear: Gear[] }) {
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[brand,setBrand]=useState('All'),[maxPrice,setMaxPrice]=useState(100),[available,setAvailable]=useState(false),[date,setDate]=useState('');
 const categories=['All',...Array.from(new Set(gear.map(x=>x.category?.name||'Other')))];const brands=['All',...Array.from(new Set(gear.map(x=>x.brand)))];
 const results=useMemo(()=>gear.filter(x=>(!query||`${x.name} ${x.brand} ${x.category?.name}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All'||x.category?.name===category)&&(brand==='All'||x.brand===brand)&&x.pricePerDay<=maxPrice&&(!available||x.availability)),[gear,query,category,brand,maxPrice,available,date]);
 return <div className="filter-layout"><aside className="filters"><div className="filter-title"><h3>Filters</h3><button onClick={()=>{setQuery('');setCategory('All');setBrand('All');setMaxPrice(100);setAvailable(false);setDate('')}}>Clear</button></div><div className="filter-group"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="filter-group"><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}>{brands.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="filter-group"><label>Up to ${maxPrice} / day<input aria-label="Maximum daily price" type="range" min="10" max="100" step="5" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label></div><div className="filter-group"><label>Pickup date<input aria-label="Availability date" type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Available now</label></div></aside><div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search gear" placeholder="Search tents, bikes, kayaks…"/><p className="muted" aria-live="polite">{results.length} pieces of gear available{date?` for ${date}`:''}</p>{results.length?<div className="gear-grid">{results.map(x=><GearCard key={x.id} gear={x}/>)}</div>:<div className="empty">No gear matches those filters. Try broadening your search.</div>}</div></div>;
}
